### ISSUE TITLE
[v0.9] `osc_receiver.rs` example crashes when `osc_sender.rs` runs with vulkan error

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#220]
Getting a strange error in the `osc_receiver.rs` example within the `Ui` renderer:

```
thread 'main' panicked at 'failed to execute future: AccessError { error: AlreadyInUse, command_name: "vkCmdCopyBufferToImage", command_param: "destination", command_offset: 0 }', libcore/result.rs:1009:5        
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /rustc/0b9f19dff1347e29bf4362ab5a8fab84b43023b5/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /rustc/0b9f19dff1347e29bf4362ab5a8fab84b43023b5/src/libcore/result.rs:835
  10: nannou::app::view_frame
             at /home/mindtree/programming/rust/nannou/src/app.rs:2011
  11: nannou::app::run_loop_mode_refresh_sync
             at /home/mindtree/programming/rust/nannou/src/app.rs:1474
  12: nannou::app::run_loop
             at /home/mindtree/programming/rust/nannou/src/app.rs:1162
  13: <nannou::app::Builder<M, E>>::run
             at /home/mindtree/programming/rust/nannou/src/app.rs:569
  14: osc_receiver::main
             at examples/osc_receiver.rs:8
  15: std::rt::lang_start::{{closure}}
             at /rustc/0b9f19dff1347e29bf4362ab5a8fab84b43023b5/src/libstd/rt.rs:74
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:398
             at libstd/rt.rs:58
  19: std::rt::lang_start
             at /rustc/0b9f19dff1347e29bf4362ab5a8fab84b43023b5/src/libstd/rt.rs:74
  20: main
  21: __libc_start_main
  22: _start
```

The example seems to run fine right until the accompanying `osc_sender.rs` example opens and sends event. I think the error has something to do with the updating text in the `Ui` causing an update in the glyph cache image which for some reason is giving us this `AlreadyInUse` error. Strange that this doesn't occur in the `simple_ui.rs` though.

**Comment by mitchmindtree** [comment]
Looks like this has been accidentally fixed by #239!
