### ISSUE TITLE
Runtime error when running example on Ubuntu: failed to create vulkan instance

### ISSUE THREAD

**Issue by CGUTA** [nannou-org/nannou#344]
Folowed instructions for Ubuntu: (On old laptop)
updated rust
cmake + python
installed drivers for AMD

executed:
```
 RUST_BACKTRACE=1 cargo run --release --example simple_draw
```
and got

```
    Finished release [optimized] target(s) in 11.99s
     Running `target/release/examples/simple_draw`
thread 'main' panicked at 'failed to create vulkan instance: InitializationFailed', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: nannou::app::Builder<M,E>::run
  10: nannou::sketch
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: main
  16: __libc_start_main
  17: _start

```

**Comment by freesig** [comment]
Hey thanks for the report.
Can you please show the output of running `vulkaninfo`

**Comment by CGUTA** [comment]
Sure thing:

```
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.70

/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:2700: failed with VK_ERROR_INITIALIZATION_FAILED
```

if it is of any help I am running Ubuntu 18.04.2 LTS

and the graphics card is
```
> lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Seymour [Radeon HD 6400M/7400M Series] (rev ff)

```

**Comment by freesig** [comment]
I checked [the amd vulkan driver website](https://www.amd.com/en/technologies/vulkan) and [gpuinfo](https://vulkan.gpuinfo.org/). It looks like unfortunately amd doesn't support vulkan for `Radeon HD 6400M/7400M Series`.
This is the hard trade off we had to make in choosing vulkan. We get better future support but we loose a bit of legacy support.

However you might be able to get support using the mesa drivers. It can work for legacy radeon but if not it should atleast allow the integrated intel to work. Definitely worth a try:
`sudo apt-get install libvulkan1 mesa-vulkan-drivers vulkan-utils`

**Comment by CGUTA** [comment]
Ahhh sorry to hear that :(, I tried the mesa drivers but they were already installed apparently.
I will see if I can run it on another computer then.

Thank you for your help!
```
libvulkan1 is already the newest version (1.1.70+dfsg1-1ubuntu0.18.04.1).
vulkan-utils is already the newest version (1.1.70+dfsg1-1ubuntu0.18.04.1).
mesa-vulkan-drivers is already the newest version (19.2~git1906120730.48d7e7~oibaf~b).
```
