### ISSUE TITLE
Raspberry PI 4 doubts

### ISSUE THREAD

**Issue by dimitre** [nannou-org/nannou#363]
Hello, it is more a contact than an issue. feel free to close it anytime.
I've tried to build on Raspberry PI 4 and I'm wondering if Vulkan support is the only thing stopping it from build this time. 
Thanks for the beautiful project.
Here is one suggestion: it would be great to have an official Telegram group for Nannou
Cheers!

**Comment by JoshuaBatty** [comment]
Hi @dimitre, yes Vulkan support is the single reason nannou can't be built on Raspberry PI at this stage. We have been discussing moving to gfx-hal and rendy in the future which may open up the possibility of have run on Raspberry PI's in the future. 

By the way, we have a nannou Slack channel where we all hang out, feel free [to join]( https://communityinviter.com/apps/nannou/nannou-slack)!

**Comment by mitchmindtree** [comment]
Also just wanted to add, there are a lot of folks eager to get Vulkan running on raspberry pi - we might get lucky and see an rpi vk driver earlier than we can get around to addressing this :crossed_fingers:  That said, we're still interested in gfx-hal as targeting the web with Vulkan has a similar story right now.

**Comment by dimitre** [comment]
Great. I've just tested with the latest, and rust nightly in RPI4
it returns
```
thread 'main' panicked at 'failed to create vulkan instance: IncompatibleDriver', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by ahirner** [comment]
@dimitre I was able to run `wgpu-rs` `hello-compute`, yet something's going on at the SwapChain creation at the level of `wgpu-rs` and also `nannou` examples: https://gitlab.freedesktop.org/apinheiro/mesa/-/issues/8

**Comment by facklambda** [comment]
Hey all, I just saw this today: https://www.cnx-software.com/2021/10/27/raspberry-pi-4-achieves-vulkan-1-1-conformance-gets-up-to-60-gpu-performance-boost/

Should indicate promising things for raspberry pi 4 support?

**Comment by mitchmindtree** [comment]
Just a heads up - I imagine #812 might make working with the Pi 4 and older versions much easier! Not quite as cool as the raspberry pi landing vulkan support though.

**Comment by jlgangwisch** [comment]
Tried to run on Raspberry pi OS 64bit with Vulkan installed, and got this error:   
thread 'main' panicked at 'could not get or request device: RequestDeviceError', /home/pi/nannou/nannou_wgpu/src/device_map.rs:220:14

Any chance anyone has a workaround?  Screenshots with backtrace attached.
![Screenshot from 2022-12-05 21-19-45](https://user-images.githubusercontent.com/28738403/205792985-46a853f1-755e-4a8a-9728-7c27c993bb67.png)

![Screenshot from 2022-12-05 21-21-09](https://user-images.githubusercontent.com/28738403/205792992-721c8ee0-14c0-48dd-92ff-26726ce10102.png)

**Comment by drac-dot-gay** [comment]
i'm looking into this at the moment and i haven't been able to find much information on what needs to be done to get it working

**Comment by tychedelia** [comment]
You'd need to investigate wgpu support on raspi.
