### ISSUE TITLE
Crash on some examples, not on others (Linux)

### ISSUE THREAD

**Issue by ErikNatanael** [nannou-org/nannou#481]
While sketching today I started noticing strange behaviour where the whole system would freeze randomly while running a nannou sketch. The system would freeze for between ~0.5 s to 4 s and then go back to normal to a couple of seconds. Having the mouse cursor enter or leave the window seems to usually trigger a freeze or sometimes a crash.

To narrow it down I had a look at the examples. The simple_text example runs fine as it is, but with this line (no 21) commented out it crashes when the mouse cursor leaves the window:
```
draw.text(text).color(BLACK).font_size(24).wh(win_rect.wh());
```
I haven't noticed this with any nannou sketch or example before today. It could be something on my system of course, but I do get a Rust error message with a backtrace. My system: Ubuntu Studio 19.10/i3wm on a Dell XPS 9560 with the Nvidia GTX 1050Ti graphics card.

When it crashes, I get one of two error messages (full backtrace):
```
thread 'main' panicked at 'key not present', src/libcore/option.rs:1185:5
stack backtrace:
   0:     0x559e5492b054 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x559e5492b054 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x559e5492b054 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x559e5492b054 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x559e5494d5ec - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x559e54928037 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x559e5492d5ae - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x559e5492d5ae - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x559e5492d5ae - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x559e5492d2a1 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x559e5492dcab - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x559e5492d84e - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x559e5492d736 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x559e549499de - core::panicking::panic_fmt::hdeb7979ab6591473
                               at src/libcore/panicking.rs:139
  14:     0x559e54949a47 - core::option::expect_failed::h6c3ec3658ee2670d
                               at src/libcore/option.rs:1185
  15:     0x559e5480a697 - wgpu_command_encoder_begin_render_pass
  16:     0x559e547e8291 - wgpu::CommandEncoder::begin_render_pass::h565e66ef6b06df53
  17:     0x559e5474cc58 - nannou::wgpu::texture::reshaper::Reshaper::encode_render_pass::hd12820c687e1fd48
  18:     0x559e54726f2f - nannou::frame::Frame::submit_inner::h884667b95b01905d
  19:     0x559e546c5c9d - simple_text::view::h61656e08a65dc384
  20:     0x559e546cb43d - nannou::app::run_loop::{{closure}}::hdb354e84cf8898cd
  21:     0x559e546cedd0 - winit::platform_impl::platform::x11::EventLoop<T>::run::hf9364aa1b9937d50
  22:     0x559e546c8d9f - winit::platform_impl::platform::EventLoop<T>::run::h6f4e63622b88b175
  23:     0x559e546e7daa - winit::event_loop::EventLoop<T>::run::h8e6828802c95694f
  24:     0x559e546e86e9 - nannou::app::SketchBuilder<E>::run::h864950826d157f1c
  25:     0x559e546c5c10 - simple_text::main::h8611f1ee4aab9053
  26:     0x559e546f1263 - std::rt::lang_start::{{closure}}::h37338e5318f603eb
  27:     0x559e5492d6d3 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  28:     0x559e5492d6d3 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  29:     0x559e54931c0a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  30:     0x559e5492e18d - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  31:     0x559e5492e18d - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  32:     0x559e5492e18d - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  33:     0x559e546c5d72 - main
  34:     0x7f539d65a1e3 - __libc_start_main
  35:     0x559e546c01ae - _start
  36:                0x0 - <unknown>
```
or
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `2`', /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/hub.rs:120:9
stack backtrace:
   0:     0x557d8e3e2054 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x557d8e3e2054 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x557d8e3e2054 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x557d8e3e2054 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x557d8e4045ec - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x557d8e3df037 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x557d8e3e45ae - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x557d8e3e45ae - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x557d8e3e45ae - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x557d8e3e42a1 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x557d8e3e4cab - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x557d8e3e484e - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x557d8e3e478f - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x557d8e2c1a31 - wgpu_command_encoder_begin_render_pass
  14:     0x557d8e29f291 - wgpu::CommandEncoder::begin_render_pass::h565e66ef6b06df53
  15:     0x557d8e203c58 - nannou::wgpu::texture::reshaper::Reshaper::encode_render_pass::hd12820c687e1fd48
  16:     0x557d8e1ddf2f - nannou::frame::Frame::submit_inner::h884667b95b01905d
  17:     0x557d8e17cc9d - simple_text::view::h61656e08a65dc384
  18:     0x557d8e18243d - nannou::app::run_loop::{{closure}}::hdb354e84cf8898cd
  19:     0x557d8e185dd0 - winit::platform_impl::platform::x11::EventLoop<T>::run::hf9364aa1b9937d50
  20:     0x557d8e17fd9f - winit::platform_impl::platform::EventLoop<T>::run::h6f4e63622b88b175
  21:     0x557d8e19edaa - winit::event_loop::EventLoop<T>::run::h8e6828802c95694f
  22:     0x557d8e19f6e9 - nannou::app::SketchBuilder<E>::run::h864950826d157f1c
  23:     0x557d8e17cc10 - simple_text::main::h8611f1ee4aab9053
  24:     0x557d8e1a8263 - std::rt::lang_start::{{closure}}::h37338e5318f603eb
  25:     0x557d8e3e46d3 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  26:     0x557d8e3e46d3 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  27:     0x557d8e3e8c0a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  28:     0x557d8e3e518d - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  29:     0x557d8e3e518d - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  30:     0x557d8e3e518d - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  31:     0x557d8e17cd72 - main
  32:     0x7fe7249bf1e3 - __libc_start_main
  33:     0x557d8e1771ae - _start
  34:                0x0 - <unknown>
```

~~Looks wgpu related, could it be a bug introduced upstream?~~ [No new wgpu version for 4 months](https://crates.io/crates/wgpu)

**Comment by ErikNatanael** [comment]
Testing on XFCE instead of i3 reveals it is losing focus that triggers the crash, not the mouse cursor in itself. Moving a window around causes either a freeze or a crash.

**Comment by ErikNatanael** [comment]
Examples that do work:
* simple_text
* simple_loop
*

**Comment by ErikNatanael** [comment]
Sorry accidental close

**Comment by mitchmindtree** [comment]
Thanks for the report @ErikNatanael!

I'm currently finishing off an overhaul for the `Draw` API, but I'll have a look into this after for sure. Nothing immediately jumps to mind, but perhaps the validation layers will show something? Do you get any more useful info during the crash if you run it with the following env var set?
```
VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation
```
e.g.
```
VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation cargo run --example simple_text
```
?
That `panic!` you're getting looks suspiciously like we're losing communication with the GPU, so I suspect enabling the vulkan validation layers (like above) might provide more useful info.

**Comment by ErikNatanael** [comment]
I ran `RUST_BACKTRACE=full VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation cargo run --example simple_text` and got this error message:
```
thread 'main' panicked at 'key not present', src/libcore/option.rs:1185:5
stack backtrace:
   0:     0x55e3aaee0324 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55e3aaee0324 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55e3aaee0324 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55e3aaee0324 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55e3aaf028fc - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55e3aaedd307 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x55e3aaee287e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55e3aaee287e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55e3aaee287e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x55e3aaee2571 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x55e3aaee2f7b - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x55e3aaee2b1e - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x55e3aaee2a06 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x55e3aaefecee - core::panicking::panic_fmt::hdeb7979ab6591473
                               at src/libcore/panicking.rs:139
  14:     0x55e3aaefed57 - core::option::expect_failed::h6c3ec3658ee2670d
                               at src/libcore/option.rs:1185
  15:     0x55e3aa99f72a - core::option::Option<T>::expect::h19859bef8afe9611
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/option.rs:345
  16:     0x55e3aa97860d - <vec_map::VecMap<V> as core::ops::index::Index<usize>>::index::h5455b3609ad44e46
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.8.1/src/lib.rs:818
  17:     0x55e3aab84045 - <wgpu_native::hub::Storage<T,I> as core::ops::index::Index<I>>::index::hee8f65bdb208960a
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/hub.rs:119
  18:     0x55e3aab0b001 - wgpu_native::command::command_encoder_begin_render_pass::{{closure}}::h9fb11acb13054ad4
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:266
  19:     0x55e3aa998bdd - core::option::Option<T>::map::hcc6d60692b5b35ea
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/option.rs:447
  20:     0x55e3aab06968 - wgpu_native::command::command_encoder_begin_render_pass::h672231f58ed31ced
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:264
  21:     0x55e3aab0c519 - wgpu_command_encoder_begin_render_pass
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:739
  22:     0x55e3aa8e2f2e - wgpu::CommandEncoder::begin_render_pass::h85c4bb364e63af5a
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:1059
  23:     0x55e3aa62006c - nannou::wgpu::render_pass::Builder::begin::hb487d1269947d368
                               at src/wgpu/render_pass.rs:206
  24:     0x55e3aa60f930 - nannou::wgpu::texture::reshaper::Reshaper::encode_render_pass::h5887559d1f31c449
                               at src/wgpu/texture/reshaper/mod.rs:122
  25:     0x55e3aa54811a - nannou::frame::Frame::submit_inner::h06cb8c9f74128c2b
                               at src/frame/mod.rs:124
  26:     0x55e3aa548960 - <nannou::frame::Frame as core::ops::drop::Drop>::drop::ha242344db673fc0a
                               at src/frame/mod.rs:320
  27:     0x55e3aa4ad575 - core::ptr::real_drop_in_place::h423b902e240aec23
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ptr/mod.rs:175
  28:     0x55e3aa4cd05e - simple_text::view::h0ffe7e320abf8594
                               at examples/simple_text.rs:24
  29:     0x55e3aa4d95fd - nannou::app::run_loop::{{closure}}::hb5e8938dfefdf052
                               at /home/erik/git/nannou/src/app.rs:1106
  30:     0x55e3aa4c944d - winit::platform_impl::platform::sticky_exit_callback::h9b36b23d37e721b7
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/mod.rs:697
  31:     0x55e3aa4f4d2c - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h55eb9c3172e380c6
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/x11/mod.rs:290
  32:     0x55e3aa4f609b - winit::platform_impl::platform::x11::EventLoop<T>::run::h41c18bfdc79f81db
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/x11/mod.rs:386
  33:     0x55e3aa4c8ec4 - winit::platform_impl::platform::EventLoop<T>::run::hc3e4f367e5ecf733
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/mod.rs:644
  34:     0x55e3aa4ab934 - winit::event_loop::EventLoop<T>::run::hc05d4077961f187a
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/event_loop.rs:148
  35:     0x55e3aa4d858c - nannou::app::run_loop::h23de6d3de76fe762
                               at /home/erik/git/nannou/src/app.rs:1000
  36:     0x55e3aa4d0cab - nannou::app::Builder<M,E>::run::h6242ae1fbccbe539
                               at /home/erik/git/nannou/src/app.rs:413
  37:     0x55e3aa4d0e22 - nannou::app::SketchBuilder<E>::run::h80f5b27d77746cf0
                               at /home/erik/git/nannou/src/app.rs:438
  38:     0x55e3aa4cce80 - simple_text::main::hd1f34ec7343772af
                               at examples/simple_text.rs:8
  39:     0x55e3aa4cec20 - std::rt::lang_start::{{closure}}::ha6f040abb8ef7360
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  40:     0x55e3aaee29a3 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  41:     0x55e3aaee29a3 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  42:     0x55e3aaee6efa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  43:     0x55e3aaee345d - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  44:     0x55e3aaee345d - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  45:     0x55e3aaee345d - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  46:     0x55e3aa4cebf9 - std::rt::lang_start::hcb4a89d43b14bbd0
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  47:     0x55e3aa4cd0da - main
  48:     0x7f66aff921e3 - __libc_start_main
  49:     0x55e3aa4a719e - _start
  50:                0x0 - <unknown>
```

**Comment by ErikNatanael** [comment]
Starting to suspect this has something to do with graphics card drivers. It works now if I use my built in graphics card (Intel HD 630) (although I'm getting another strange bug there, I'll write separately), but not with the Nvidia card. I'm using prime-select to switch between them. 

On my other install running Manjaro I'm using a different driver with [PRIME render offload](https://wiki.archlinux.org/index.php/PRIME#PRIME_render_offload) which should still select the same Intel card by default and there all the nannou examples crash right away with a slightly different error message:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5
stack backtrace:
   0:     0x5564527415e4 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5564527415e4 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5564527415e4 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x5564527415e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x556452761aac - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x55645273e567 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x5564527437e5 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5564527437e5 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5564527437e5 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x5564527434d1 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x556452743e4a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x556452743a30 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x55645275f941 - core::panicking::panic_fmt::hb1f3e14b86a3520c
                               at src/libcore/panicking.rs:85
  13:     0x55645275f88d - core::panicking::panic::hcdc9f0ba8d71d265
                               at src/libcore/panicking.rs:52
  14:     0x556452218367 - core::option::Option<T>::unwrap::h306ef1082e445e8b
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/macros/mod.rs:10
  15:     0x556452354e56 - wgpu_request_adapter
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474
  16:     0x5564521ae4fe - wgpu::Adapter::request::h922b3b3e0540ee9d
                               at /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  17:     0x556451e5013d - nannou::wgpu::device_map::AdapterMap::get_or_request::hd4ba7770c7e21f8c
                               at src/wgpu/device_map.rs:81
  18:     0x556451e455f6 - nannou::window::Builder::build::h0a518df369540379
                               at src/window.rs:738
  19:     0x556451e0cc7f - nannou::app::Builder<M,E>::run::ha73450e149a233b7
                               at /run/media/erik/68a608bb-cd23-4a71-a35d-555b1910c8a1/home/erik/git/nannou/src/app.rs:396
  20:     0x556451e0d1d2 - nannou::app::SketchBuilder<E>::run::h09ccb1b17b1184e5
                               at /run/media/erik/68a608bb-cd23-4a71-a35d-555b1910c8a1/home/erik/git/nannou/src/app.rs:438
  21:     0x556451e011b0 - simple_text::main::hb1d5d422e7c0a8e1
                               at examples/simple_text.rs:8
  22:     0x556451dea120 - std::rt::lang_start::{{closure}}::hd5f918fedea28e2f
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  23:     0x556452743913 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  24:     0x556452743913 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  25:     0x556452747e07 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  26:     0x5564527442f0 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  27:     0x5564527442f0 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  28:     0x5564527442f0 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  29:     0x556451dea0f9 - std::rt::lang_start::h6e6c18565d06243b
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  30:     0x556451e0141a - main
  31:     0x7fceef118023 - __libc_start_main
  32:     0x556451dd719e - _start
  33:                0x0 - <unknown>
```

**Comment by ErikNatanael** [comment]
Everything now works perfectly on my Manjaro install using the hybrid driver (no idea what changed). After updating my ubuntu driver it no longer crashes when using the dedicated graphics card and the window loses focus (although it freezes for a few seconds). I'm gonna call that a win and say it's a driver issue somewhere, there are many nvidia drivers to choose from so picking the best one seems to do the trick here.
Sorry for all the noise!

**Comment by mitchmindtree** [comment]
No worries at all, thanks for the update! This kind of thing always has the potential to be useful to future users, especially if they might have a similar setup. it also helps us to point users in the right direction when they report similar issues :) Glad you got your nvidia card working!
