### ISSUE TITLE
Crash on audio examples

### ISSUE THREAD

**Issue by Drowrin** [nannou-org/nannou#483]
On running `cargo run --release --example simple_audio` or `cargo run --release --example simple_audio_file` I get the error message "Cannot change thread mode after it is set." shortly after the window launches, before any audio plays. This only happens for the audio examples.

I am on Windows 10, with rust 1.43.0-nightly (2020-03-14). This happens on either nannou 0.13.1 or by cloning the repository and running examples there.

Full backtrace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: -2147417850, kind: Other, message: "Cannot change thread mode after it is set." }', C:\Users\drowrin\.cargo\registry\src\github.com-1ecc6299db9ec823\cpal-0.10.0\src\host\wasapi\com.rs:13:9
stack backtrace:
   0:     0x7ff6a42e89ef - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1:     0x7ff6a42e89ef - std::sys_common::backtrace::_print_fmt
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\sys_common\backtrace.rs:78
   2:     0x7ff6a42e89ef - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff6a42fdb9b - core::fmt::write
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libcore\fmt\mod.rs:1069
   4:     0x7ff6a42e57cc - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\io\mod.rs:1427
   5:     0x7ff6a42ebcec - std::sys_common::backtrace::_print
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\sys_common\backtrace.rs:62
   6:     0x7ff6a42ebcec - std::sys_common::backtrace::print
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\sys_common\backtrace.rs:49
   7:     0x7ff6a42ebcec - std::panicking::default_hook::{{closure}}
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\panicking.rs:198
   8:     0x7ff6a42eb93f - std::panicking::default_hook
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\panicking.rs:218
   9:     0x7ff6a42ec4d7 - std::panicking::rust_panic_with_hook
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\panicking.rs:509
  10:     0x7ff6a42ec05f - std::panicking::begin_panic_handler
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\panicking.rs:417
  11:     0x7ff6a42fb810 - core::panicking::panic_fmt
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libcore\panicking.rs:111
  12:     0x7ff6a42fb653 - core::option::expect_none_failed
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libcore\option.rs:1211
  13:     0x7ff6a40c9559 - std::thread::local::fast::Key<T>::try_initialize::h2d8e2299c4291e41
  14:     0x7ff6a40c93da - cpal::host::wasapi::device::default_device::ha069057da4da1326
  15:     0x7ff6a42e7e64 - std::sync::once::Once::call_inner
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\sync\once.rs:416
  16:     0x7ff6a40c920b - cpal::host::wasapi::device::default_device::ha069057da4da1326
  17:     0x7ff6a409a3de - nannou_audio::stream::output::Builder<M,FA,FB,S>::build::h161551a489f8cda8
  18:     0x7ff6a409909c - <std::collections::hash::map::DefaultHasher as core::hash::Hasher>::write::h008cafbb9da75f14
  19:     0x7ff6a40a67d1 - nannou::app::Builder<M,E>::run::h948b28e1fa86038a
  20:     0x7ff6a4098b41 - <std::collections::hash::map::DefaultHasher as core::hash::Hasher>::write::h008cafbb9da75f14
  21:     0x7ff6a409e5d6 - <palette::rgb::rgb::Rgb<palette::encoding::srgb::Srgb,T> as nannou::color::conv::IntoLinSrgba<S>>::into_lin_srgba::h8e71ac306cc10e19
  22:     0x7ff6a42ec7fa - std::rt::lang_start_internal::{{closure}}
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\rt.rs:52
  23:     0x7ff6a42ec7fa - std::panicking::try::do_call
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\panicking.rs:329
  24:     0x7ff6a42ec7fa - std::panicking::try::do_try
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\panicking.rs:285
  25:     0x7ff6a42ec7fa - std::panicking::try
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\panicking.rs:274
  26:     0x7ff6a42ec7fa - std::panic::catch_unwind
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\panic.rs:394
  27:     0x7ff6a42ec7fa - std::rt::lang_start_internal
                               at /rustc/7cdbc87a49b0b705a41a004a6d486b0952521ae7\/src\libstd\rt.rs:51
  28:     0x7ff6a4099cf7 - main
  29:     0x7ff6a4399b50 - invoke_main
                               at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  30:     0x7ff6a4399b50 - __scrt_common_main_seh
                               at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  31:     0x7ffdb74d4034 - BaseThreadInitThunk
  32:     0x7ffdb9533691 - RtlUserThreadStart
error: process didn't exit successfully: `target\release\examples\simple_audio.exe` (exit code: 101)
```

**Comment by mitchmindtree** [comment]
Thanks for the report!

I get the feeling that this might have something to do with both [cpal](https://github.com/RustAudio/cpal) and [winit](https://github.com/rust-windowing/winit) attempting to set the COM thread mode on windows. It looks like the `panic!` occurs when CPAL attempts to do so, which makes sense as winit's event loop initialisation process runs earlier. rustaudio/cpal#59 may have something to do with it - the issue never used to cause a `panic!`, but winit has undergone an extensive overhaul recently which may have involved a change that causes CPAL to `panic!`.

@Drowrin could you possibly try running the `beep.rs` example at the [cpal repo](https://github.com/RustAudio/cpal)? If this works OK for you, it will help to further confirm my suspicion that the issue only occurs when trying to spawn a stream on windows after a winit event loop has been created.

**Comment by Drowrin** [comment]
Thanks for looking into this. The `beep.rs` example in the cpal repo does work as intended.

**Comment by diegodorado** [comment]
Having the same error here, windows 10

**Comment by danwilhelm** [comment]
As a temporary workaround, you can build a custom `winit` with drag-and-drop disabled. Then build `nannou` with the custom `winit` build. This allows the `cpal` and `winit` threads to coexist. Thanks to @MacTuitui for these steps:

- Clone `winit`: https://github.com/rust-windowing/winit
- Set `drag_and_drop` to `false` here: https://github.com/rust-windowing/winit/blob/master/src/platform_impl/windows/mod.rs#L42
- Add to the root `Cargo.toml`:
