### ISSUE TITLE
Crash when resizing window quickly multiple times.

### ISSUE THREAD

**Issue by edap** [nannou-org/nannou#491]
When resizing the window quickly on linux, the application crash.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AllocationError(OutOfMemory(Device))', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Version 0.13.1

**Comment by mitchmindtree** [comment]
Thanks for the report! I'm also noticing this on Linux when resizing for a while. It seems we have some textures or some other resource that isn't being cleaned up properly. I'm not sure if its us that should be releasing the resources of it its a leak in wgpu. Will have to do some investigating with `renderdoc`!

**Comment by tpltnt** [comment]
Can confirm. Longer backtrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AllocationError(OutOfMemory(Device))', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933
  16: wgpu_native::device::Device<B>::create_texture
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/device.rs:734
  17: wgpu_native::device::device_create_texture
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/device.rs:914
  18: wgpu_device_create_texture
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/device.rs:935
  19: wgpu::Device::create_texture
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:817
  20: nannou::wgpu::texture::Builder::build
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.13.1/src/wgpu/texture/mod.rs:368
  21: nannou::frame::create_lin_srgba_texture
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.13.1/src/frame/mod.rs:339
  22: nannou::frame::create_intermediary_lin_srgba
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.13.1/src/frame/mod.rs:359
  23: nannou::frame::RenderData::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.13.1/src/frame/mod.rs:298
  24: nannou::window::Window::rebuild_swap_chain
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.13.1/src/window.rs:1283
  25: nannou::app::run_loop::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.13.1/src/app.rs:1160
  26: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/x11/mod.rs:413
  27: winit::platform_impl::platform::sticky_exit_callback
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/mod.rs:697
  28: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/x11/mod.rs:402
  29: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/x11/event_processor.rs:475
  30: winit::platform_impl::platform::x11::EventLoop<T>::drain_events
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/x11/mod.rs:401
  31: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/x11/mod.rs:260
  32: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/x11/mod.rs:386
  33: winit::platform_impl::platform::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/platform_impl/linux/mod.rs:644
  34: winit::event_loop::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.21.0/src/event_loop.rs:148
  35: nannou::app::run_loop
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.13.1/src/app.rs:1000
  36: nannou::app::Builder<M,E>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.13.1/src/app.rs:413
  37: nannou::app::SketchBuilder<E>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.13.1/src/app.rs:438
  38: perlin_noise_field::main
             at src/main.rs:9
  39: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  40: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  41: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  42: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  43: std::panicking::try
             at src/libstd/panicking.rs:265
  44: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  45: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  46: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  47: main
  48: __libc_start_main
  49: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mitchmindtree** [comment]
Possibly related https://github.com/gfx-rs/wgpu-rs/issues/136

**Comment by jmg-duarte** [comment]
This happened to me! 

I've uploaded the repository.
https://github.com/jmg-duarte/nannou-bubble-sort

**Comment by hypopyon** [comment]
I think this has to do with WM differences, winit's event loop, and possibly wgpu's memory allocator. There are too many ```Resized``` events occuring at the same time (sometimes hundreds in a shorter time than it takes to render a frame iirc.) Wgpu can't keep up with that amount of swapchains being created and marked for deletion.

In my own experimentation with wgpu I've found this can be fixed by delaying the replacement of an invalidated swapchain until the next ```RedrawRequested``` event. This _shouldn't_ affect how smooth resizing is (if anything it should improve it) but I've found through many fruitless attempts that trying to get resizing perfect with winit is a fool's errand. Or at the very least, a fool other than me.

I'll see what I can do, but I'm not yet familiar with nannou's event loop.

**Comment by hypopyon** [comment]
So after a few attempt to follow through on my previous theory, I wasn't able to solve the problem. I did however see that the crash typically happened in encode_render_pass or rebuild_swapchain. After checking renderdoc, it seems like there's some leak for shader modules, samplers, pipeline layouts, pipelines, texture descriptors... pretty much everything except the swapchain surprisingly enough. I tried some of the wgpu examples and wasn't able to reproduce the issue so it's likely it's on nannou's end. I'm not quite sure what could be causing such a leak.. at the very least nothing stood out to me.

**Comment by hypopyon** [comment]
Same thing happens on Windows.

**Comment by dzil123** [comment]
Is there any progress on this issue? I get the following error on Linux when running the [window-coordinates.rs](https://github.com/nannou-org/nannou/blob/44e6ae445021e1ae315082ba461dde563a63b594/examples/nannou_basics/window_coordinates.rs) example.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AllocationError(OutOfMemory(Device))', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/device.rs:744:14
```
