### ISSUE TITLE
generative example m_1_3_03 failing

### ISSUE THREAD

**Issue by salkin-mada** [nannou-org/nannou#546]
# info
System: Arch Linux x86_64 5.6.3-arch1-1
Wm: Sway (Wayland)

* could the issue be that i am using `intel-mesa`? (Haswell Vulkan support is incomplete)

## Reproducer
* running the example:
```
nannou git:(master) RUST_BACKTRACE=full cargo run --release --example m_1_3_03
```
* throws:
``` 
    Finished release [optimized] target(s) in 0.26s
     Running `target/release/examples/m_1_3_03`
INTEL-MESA: warning: Haswell Vulkan support is incomplete
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `7854496`,
 right: `2097152`', nannou/src/wgpu/texture/mod.rs:269:9
stack backtrace:
   0:     0x55f701e4d0a4 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55f701e4d0a4 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55f701e4d0a4 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55f701e4d0a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55f701e6d80c - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x55f701e49f47 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x55f701e4f2a5 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55f701e4f2a5 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55f701e4f2a5 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x55f701e4ef91 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x55f701e4f90a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x55f701e4f4f0 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:     0x55f701e4f46b - std::panicking::begin_panic_fmt::h3f391831d1286dec
                               at src/libstd/panicking.rs:334
  13:     0x55f701c195ac - nannou::wgpu::texture::Texture::upload_data::h9b18c781aabed033
  14:     0x55f701bcf3b8 - m_1_3_03::view::h76b8ebeac7300143
  15:     0x55f701bc64bd - nannou::app::run_loop::{{closure}}::h49ff76bfa2a9dfae
  16:     0x55f701bdcf5a - winit::platform_impl::platform::wayland::window::WindowStore::for_each_redraw_trigger::he128b8e6b021e300
  17:     0x55f701bc1808 - winit::platform_impl::platform::wayland::event_loop::EventL
oop<T>::run::hc5953ffbae5df4f8
  18:     0x55f701bc576e - winit::platform_impl::platform::EventLoop<T>::run::hd88e344e3e9825da
  19:     0x55f701be2aca - winit::event_loop::EventLoop<T>::run::hc9cac54793cddb5d
  20:     0x55f701be3526 - nannou::app::Builder<M,E>::run::h51a86566a4694057
  21:     0x55f701bce991 - m_1_3_03::main::hfd380b377ea791d9
  22:     0x55f701bdbff3 - std::rt::lang_start::{{closure}}::h86eac8b130ca05f6
  23:     0x55f701e4f3d3 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  24:     0x55f701e4f3d3 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  25:     0x55f701e53b27 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  26:     0x55f701e4fe70 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  27:     0x55f701e4fe70 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  28:     0x55f701e4fe70 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  29:     0x55f701bcf982 - main
  30:     0x7f211f24f023 - __libc_start_main
  31:     0x55f701bb61be - _start
  32:                0x0 - <unknown>
```

**Comment by mitchmindtree** [comment]
Thanks for the issue @salkin-mada!

I have a very similar setup to you (running vulkan-intel on Linux) and I'm able to run the example:

![Screenshot from 2020-04-18 17-36-08](https://user-images.githubusercontent.com/4587373/79641970-1e826f00-819b-11ea-8cfe-450106d73ca3.png)

However! I get a very similar issue to you as soon as I try to resize the window whatsoever. My guess is that your tiling manager attempts to resize the window immediately after creation however as the example doesn't account for resizing nicely it panics immediately.

@JoshuaBatty maybe it's worth going over these examples and check they can handle resizing? At least not `panic!`ing anyways. I'm down to help out :+1:
