### ISSUE TITLE
Sketch panics

### ISSUE THREAD

**Issue by Halmela** [nannou-org/nannou#591]
I tried to run [sketch template](https://github.com/nannou-org/nannou/blob/master/examples/templates/template_sketch.rs), as
```
use nannou::prelude::*;                                        
fn main() {
    nannou::sketch(view).run()
}

fn view(app: &App, frame: Frame) {
     let draw = app.draw();
     draw.to_frame(app, &frame).unwrap();
}   
```

 but it panics with:
`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', `/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:5`

Running with `RUST_BACKTRACE=1`:

```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace
/libunwind.rs:86

   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378

  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::panicking::panic
             at src/libcore/panicking.rs:52
  14: core::option::Option<T>::unwrap
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libcore/macros/mod.rs:10
  15: wgpu_request_adapter
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474
  16: wgpu::Adapter::request
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
  17: nannou::wgpu::device_map::AdapterMap::get_or_request
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.14.0/src/wgpu
/device_map.rs:81
  18: nannou::window::Builder::build
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.14.0
/src/window.rs:741
  19: nannou::app::Builder<M,E>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.14.0/src/app.rs:395
  20: nannou::app::SketchBuilder<E>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.14.0/src/app.rs:437
  21: testings::main
             at src/main.rs:4
  22: std::rt::lang_start::{{closure}}
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  26: std::panicking::try
             at src/libstd/panicking.rs:281
  27: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  28: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  29: std::rt::lang_start
             at /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550/src/libstd/rt.rs:67
  30: main
  31: __libc_start_main
  32: _start
````

nannou 0.14.0
rustc 1.43.0
Arch Linux x64

**Comment by mitchmindtree** [comment]
Hi @Halmela, thanks for the issue!

Nannou uses Vulkan for graphics on Linux, which means the necessary vulkan drivers must be installed on your system. It looks as though wgpu was unable to find a compatible graphics device, meaning it could not find any valid devices via the Vulkan API. Could you maybe do a search for installing Vulkan drivers for you platform and graphics device? Once installed, the examples should work. If they still do not work, could you try running `vulkaninfo` and sharing the output with us? This will help us to determine if there are any incompatibilities with your device and nannou.

#585 is related.

**Comment by Halmela** [comment]
Hi!
Installing `vulkan-radeon` driver worked unlike amdvlk. I can run the examples, but it prints:
`WARNING: radv is not a conformant vulkan implementation, testing use only.`
