### ISSUE TITLE
Example draw_blend does not run

### ISSUE THREAD

**Issue by wataru358** [nannou-org/nannou#612]
Hi, I'm pretty new to Rust and Nannou, and really looking forward to working with this! 

Steps to reproduce:
- Install rust, rustup, etc per doc
- do `cargo run --release --example draw_blend`

Expected:
- example runs

Actual:
- rust window quits and cli gets error message

Log:
```
bash:nannou username$ RUST_BACKTRACE=full cargo run --example draw_blend
   Compiling libc v0.2.70
   Compiling autocfg v1.0.0
   Compiling cfg-if v0.1.10
   Compiling proc-macro2 v1.0.17
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.23
   Compiling bitflags v1.2.1
   Compiling byteorder v1.3.4
   Compiling lazy_static v1.4.0
   Compiling maybe-uninit v2.0.0
   Compiling log v0.4.8
   Compiling scopeguard v1.1.0
   Compiling memchr v2.3.3
   Compiling getrandom v0.1.14
   Compiling core-foundation-sys v0.7.0
   Compiling rand_core v0.4.2
   Compiling vec_map v0.8.2
   Compiling block v0.1.6
   Compiling serde v1.0.110
   Compiling adler32 v1.0.4
   Compiling foreign-types-shared v0.1.1
   Compiling rustc-serialize v0.3.24
   Compiling ppv-lite86 v0.2.8
   Compiling autocfg v0.1.7
   Compiling arrayvec v0.5.1
   Compiling glob v0.2.11
   Compiling regex v0.2.11
   Compiling ucd-util v0.1.8
   Compiling slab v0.4.2
   Compiling typenum v1.12.0
   Compiling libloading v0.4.3
   Compiling unicode-xid v0.1.0
   Compiling utf8-ranges v1.0.4
   Compiling rayon-core v1.7.0
   Compiling smallvec v1.4.0
   Compiling unicode-width v0.1.7
   Compiling siphasher v0.3.3
   Compiling strsim v0.8.0
   Compiling atom v0.3.5
   Compiling ansi_term v0.11.0
   Compiling fixedbitset v0.1.9
   Compiling bindgen v0.32.3
   Compiling lzw v0.10.0
   Compiling copyless v0.1.4
   Compiling arrayref v0.3.6
   Compiling proc-macro-nested v0.1.4
   Compiling color_quant v1.0.1
   Compiling byte-tools v0.2.0
   Compiling peeking_take_while v0.1.2
   Compiling either v1.5.3
   Compiling piston-float v0.3.0
   Compiling range-alloc v0.1.0
   Compiling futures-core v0.3.5
   Compiling ryu v1.0.4
   Compiling rustc-hash v1.1.0
   Compiling instant v0.1.4
   Compiling stable_deref_trait v1.1.1
   Compiling proc-macro-hack v0.5.15
   Compiling crc32fast v1.2.0
   Compiling once_cell v1.4.0
   Compiling futures-sink v0.3.5
   Compiling fake-simd v0.1.2
   Compiling linked-hash-map v0.5.3
   Compiling scoped_threadpool v0.1.9
   Compiling same-file v1.0.6
   Compiling fnv v1.0.7
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.5
   Compiling failure_derive v0.1.8
   Compiling cgmath v0.17.0
   Compiling gimli v0.21.0
   Compiling itoa v0.4.5
   Compiling remove_dir_all v0.5.2
   Compiling core-foundation-sys v0.6.2
   Compiling bytemuck v1.2.0
   Compiling anymap v0.12.1
   Compiling dispatch v0.2.0
   Compiling fixedbitset v0.2.0
   Compiling rustc-demangle v0.1.16
   Compiling cpal v0.11.0
   Compiling object v0.19.0
   Compiling find_folder v0.3.0
   Compiling notosans v0.1.0
   Compiling conrod_winit v0.70.0
   Compiling interpolation v0.1.0
   Compiling itertools v0.4.19
   Compiling sample v0.9.1
   Compiling claxon v0.4.2
   Compiling alac v0.3.3
   Compiling hound v3.4.0
   Compiling sample v0.10.0
   Compiling thread_local v0.3.6
   Compiling lock_api v0.3.4
   Compiling foreign-types v0.3.2
   Compiling inflate v0.3.4
   Compiling miniz_oxide v0.3.6
   Compiling inflate v0.4.5
   Compiling rand_core v0.3.1
   Compiling num-traits v0.2.11
   Compiling num-integer v0.1.42
   Compiling crossbeam-utils v0.7.2
   Compiling num-iter v0.1.40
   Compiling memoffset v0.5.4
   Compiling crossbeam-epoch v0.8.2
   Compiling num-bigint v0.2.6
   Compiling num-rational v0.2.4
   Compiling num-complex v0.2.4
   Compiling indexmap v1.3.2
   Compiling regex-syntax v0.5.6
   Compiling proc-macro2 v0.2.3
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling textwrap v0.11.0
   Compiling hibitset v0.6.3
   Compiling phf_shared v0.8.0
   Compiling petgraph v0.4.13
   Compiling clang-sys v0.21.2
   Compiling block-buffer v0.3.3
   Compiling piston-viewport v0.5.0
   Compiling gif v0.9.2
   Compiling gif v0.10.3
   Compiling owning_ref v0.3.3
   Compiling futures-channel v0.3.5
   Compiling futures-task v0.3.5
   Compiling walkdir v2.3.1
   Compiling storage-map v0.2.0
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0
   Compiling addr2line v0.12.1
   Compiling quote v0.4.2
   Compiling phf v0.8.0
   Compiling daggy v0.5.0
   Compiling daggy v0.6.0
   Compiling log v0.3.9
   Compiling smallvec v0.6.13
   Compiling aho-corasick v0.6.10
   Compiling fxhash v0.2.1
   Compiling stb_truetype v0.3.1
   Compiling deflate v0.7.20
   Compiling deflate v0.8.4
   Compiling tiff v0.4.0
   Compiling ogg v0.5.1
   Compiling rosc v0.1.6
   Compiling ether-dream v0.2.5
   Compiling caf v0.1.0
   Compiling quote v1.0.6
   Compiling jobserver v0.1.21
   Compiling rand v0.4.6
   Compiling malloc_buf v0.0.6
   Compiling num_cpus v1.13.0
   Compiling raw-window-handle v0.3.3
   Compiling core-foundation v0.7.0
   Compiling memchr v1.0.2
   Compiling parking_lot_core v0.7.2
   Compiling atty v0.2.14
   Compiling which v1.0.5
   Compiling rand_os v0.1.3
   Compiling rand_jitter v0.1.4
   Compiling fsevent-sys v3.0.0
   Compiling filetime v0.2.10
   Compiling rand v0.5.6
   Compiling backtrace v0.3.48
   Compiling lewton v0.7.0
   Compiling nannou_osc v0.14.0 (/Users/username/personal/nannou/nannou_osc)
   Compiling generic-array v0.9.0
   Compiling png v0.16.3
   Compiling cc v1.0.54
   Compiling threadpool v1.8.1
   Compiling gfx-hal v0.5.0
   Compiling rand_core v0.5.1
   Compiling nom v3.2.1
   Compiling clap v2.33.1
   Compiling fsevent v2.0.1
   Compiling parking_lot v0.10.2
   Compiling core-graphics v0.19.0
   Compiling crossbeam-queue v0.2.1
   Compiling crossbeam-channel v0.4.2
   Compiling parking_lot_core v0.2.14
   Compiling rand v0.3.23
   Compiling petgraph v0.5.1
   Compiling digest v0.7.6
   Compiling approx v0.3.2
   Compiling euclid v0.20.12
   Compiling ordered-float v1.0.2
   Compiling num-traits v0.1.43
   Compiling num-complex v0.1.43
   Compiling sid v0.6.1
   Compiling pennereq v0.3.1
   Compiling audrey v0.2.0
   Compiling cmake v0.1.44
   Compiling env_logger v0.4.3
   Compiling rand_chacha v0.2.2
   Compiling rand_pcg v0.2.1
   Compiling objc_exception v0.1.2
   Compiling spirv_cross v0.20.0
   Compiling cexpr v0.2.3
   Compiling crossbeam-deque v0.7.3
   Compiling parking_lot v0.4.8
   Compiling sha2 v0.7.1
   Compiling num-bigint v0.1.44
   Compiling enum_primitive v0.1.1
   Compiling lasy v0.4.1
   Compiling lyon_geom v0.15.3
   Compiling rand v0.7.3
   Compiling rusttype v0.8.3
   Compiling chashmap v2.2.2
   Compiling glsl-to-spirv v0.1.7
   Compiling png v0.11.0
   Compiling synstructure v0.12.3
   Compiling num-rational v0.1.42
   Compiling gfx-backend-empty v0.5.0
   Compiling gfx-descriptor v0.1.0
   Compiling gfx-memory v0.1.3
   Compiling lyon_path v0.15.2
   Compiling notify v5.0.0-pre.2
   Compiling rayon v1.3.0
   Compiling phf_generator v0.8.0
   Compiling tempfile v3.1.0
   Compiling num v0.1.42
   Compiling num v0.2.1
   Compiling lyon_tessellation v0.15.8
   Compiling lyon_algorithms v0.15.0
   Compiling phf_codegen v0.8.0
   Compiling envelope v0.8.1
   Compiling serde_derive v1.0.110
   Compiling peek-poke-derive v0.2.1
   Compiling thiserror-impl v1.0.19
   Compiling pin-project-internal v0.4.17
   Compiling conrod_derive v0.70.0
   Compiling futures-macro v0.3.5
   Compiling zerocopy-derive v0.2.0
   Compiling palette_derive v0.5.0
   Compiling palette v0.5.0
   Compiling lyon v0.15.8
   Compiling peek-poke v0.2.0
   Compiling jpeg-decoder v0.1.19
   Compiling thiserror v1.0.19
   Compiling zerocopy v0.3.0
   Compiling wgpu-types v0.5.1
   Compiling image v0.18.0
   Compiling image v0.23.4
   Compiling failure v0.1.8
   Compiling pin-project v0.4.17
   Compiling ilda-idtf v0.1.0
   Compiling futures-util v0.3.5
   Compiling nannou_laser v0.14.3 (/Users/username/personal/nannou/nannou_laser)
   Compiling noise v0.6.0
   Compiling coreaudio-sys v0.2.2
   Compiling objc v0.2.7
   Compiling cocoa v0.20.1
   Compiling objc_id v0.1.1
   Compiling core-video-sys v0.1.4
   Compiling objc-foundation v0.1.1
   Compiling copypasta v0.6.3
   Compiling futures-executor v0.3.5
   Compiling futures v0.3.5
   Compiling metal v0.18.0
   Compiling winit v0.22.2
   Compiling pistoncore-input v0.24.0
   Compiling serde_json v1.0.53
   Compiling toml v0.5.6
   Compiling pitch_calc v0.12.0
   Compiling time_calc v0.13.0
   Compiling isf v0.1.0 (https://github.com/nannou-org/isf#99424e5b)
   Compiling conrod_core v0.70.0
   Compiling nannou_timeline v0.14.0 (/Users/username/personal/nannou/nannou_timeline)
   Compiling gfx-auxil v0.4.0
   Compiling gfx-backend-metal v0.5.2
   Compiling hotglsl v0.1.0 (https://github.com/nannou-org/hotglsl#0066deaf)
   Compiling wgpu-core v0.5.5
   Compiling coreaudio-rs v0.9.1
   Compiling nannou_audio v0.14.0 (/Users/username/personal/nannou/nannou_audio)
   Compiling wgpu-native v0.5.0
   Compiling wgpu v0.5.0
   Compiling conrod_wgpu v0.70.0
   Compiling nannou v0.14.1 (/Users/username/personal/nannou/nannou)
   Compiling nannou_isf v0.1.0 (/Users/username/personal/nannou/nannou_isf)
   Compiling examples v0.1.0 (/Users/username/personal/nannou/examples)
    Finished dev [unoptimized + debuginfo] target(s) in 4m 59s
     Running `target/debug/examples/draw_blend`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IncompatibleBindGroup. The current render pipeline has a layout which is incompatible with a currently set bind group. They first differ at entry index 2.', /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.5/src/command/render.rs:1150:21
stack backtrace:
   0:        0x1073fd4ff - backtrace::backtrace::libunwind::trace::hfff3154c85fa162b
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:        0x1073fd4ff - backtrace::backtrace::trace_unsynchronized::h4a9920525cd627b4
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:        0x1073fd4ff - std::sys_common::backtrace::_print_fmt::h972e000d0e4ed1fa
                               at src/libstd/sys_common/backtrace.rs:78
   3:        0x1073fd4ff - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdfed66b3e2e8ce60
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x10741ab3e - core::fmt::write::h9de7b13cfaa80b03
                               at src/libcore/fmt/mod.rs:1063
   5:        0x1073faa67 - std::io::Write::write_fmt::h9197012b9d65a9a3
                               at src/libstd/io/mod.rs:1426
   6:        0x1073ff53a - std::sys_common::backtrace::_print::hb8e24d3c51344086
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x1073ff53a - std::sys_common::backtrace::print::h93407cb3f8a6ecb3
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x1073ff53a - std::panicking::default_hook::{{closure}}::h7b209cdc44c5777f
                               at src/libstd/panicking.rs:204
   9:        0x1073ff27c - std::panicking::default_hook::hf135bc502e6f77db
                               at src/libstd/panicking.rs:224
  10:        0x1073ffba8 - std::panicking::rust_panic_with_hook::h7967810bc33e523b
                               at src/libstd/panicking.rs:470
  11:        0x1073ff772 - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:        0x10742ac6f - core::panicking::panic_fmt::h9eea9e4965bd189c
                               at src/libcore/panicking.rs:85
  13:        0x10742ab75 - core::option::expect_none_failed::ha68a01397bf24c9a
                               at src/libcore/option.rs:1211
  14:        0x106de2721 - core::result::Result<T,E>::unwrap::hd89496db367d7754
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/result.rs:1003
  15:        0x106d7c53d - wgpu_core::command::render::<impl wgpu_core::hub::Global<G>>::command_encoder_run_render_pass::hc3447a58492b7868
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.5/src/command/render.rs:1150
  16:        0x106e0cef1 - wgpu_render_pass_end_pass
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.5.0/src/command.rs:101
  17:        0x106cfb80f - <wgpu::RenderPass as core::ops::drop::Drop>::drop::hc4ade2a4aa812c7c
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.5.0/src/lib.rs:1542
  18:        0x106a6ab71 - core::ptr::drop_in_place::h59adb9db4017d025
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ptr/mod.rs:177
  19:        0x106a50415 - nannou::draw::renderer::Renderer::encode_render_pass::h4d6c69f5e2e74c38
                               at nannou/src/draw/renderer/mod.rs:894
  20:        0x106a5076a - nannou::draw::renderer::Renderer::render_to_frame::h7865cce5ba55ad38
                               at nannou/src/draw/renderer/mod.rs:934
  21:        0x106a99791 - nannou::app::<impl nannou::draw::Draw>::to_frame::ha3f6b8b71ab35196
                               at nannou/src/app.rs:911
  22:        0x106a0d129 - draw_blend::view::hd8ac65399e0463c3
                               at examples/draw/draw_blend.rs:86
  23:        0x106a23ddb - nannou::app::run_loop::{{closure}}::h3bb60fa7cbd82120
                               at /Users/username/personal/nannou/nannou/src/app.rs:1128
  24:        0x106a0dfd7 - <alloc::boxed::Box<F> as core::ops::function::FnMut<A>>::call_mut::hfb4cdcda8f2b21c9
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1024
  25:        0x106a25c13 - <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::h6abe527ce1f2d8d4
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/app_state.rs:71
  26:        0x106c96b7f - winit::platform_impl::platform::app_state::Handler::handle_nonuser_event::h3bd9676ddde3b5cd
  27:        0x106c98abd - winit::platform_impl::platform::app_state::AppState::cleared::h76ef5267aaeef01f
  28:        0x106c91d5e - winit::platform_impl::platform::observer::control_flow_end_handler::h82333a14a9d98c18
  29:     0x7fff2ffc06d8 - <unknown>
  30:     0x7fff2ffc060d - <unknown>
  31:     0x7fff2ff62e57 - <unknown>
  32:     0x7fff2ff6266e - <unknown>
  33:     0x7fff2f1c11ab - <unknown>
  34:     0x7fff2f1c0ee5 - <unknown>
  35:     0x7fff2f1c0c76 - <unknown>
  36:     0x7fff2d55877d - <unknown>
  37:     0x7fff2d55746b - <unknown>
  38:     0x7fff2d551588 - <unknown>
  39:        0x10736fed6 - <() as objc::message::MessageArguments>::invoke::h5afc7958099737e5
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128
  40:        0x10736cc9d - objc::message::platform::send_unverified::h285c41b96c3de9d8
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27
  41:        0x106a0f906 - objc::message::send_message::hc853223210c49bcb
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178
  42:        0x106a0f906 - winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::hc79b5b5d2e4fb4d0
                               at /Users/username/personal/nannou/<::objc::macros::msg_send macros>:15
  43:        0x106a0fb64 - winit::platform_impl::platform::event_loop::EventLoop<T>::run::hdb43652d7c66792d
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:89
  44:        0x106a19ae3 - winit::event_loop::EventLoop<T>::run::h51cfbab45bb981d4
                               at /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149
  45:        0x106a23209 - nannou::app::run_loop::hde8b0c8b55e8116f
                               at /Users/username/personal/nannou/nannou/src/app.rs:1020
  46:        0x106a1cbde - nannou::app::Builder<M,E>::run::hb8f4dac19fefa6b3
                               at /Users/username/personal/nannou/nannou/src/app.rs:471
  47:        0x106a1cd11 - nannou::app::SketchBuilder<E>::run::he5b80757901b9ae2
                               at /Users/username/personal/nannou/nannou/src/app.rs:496
  48:        0x106a0c2b1 - draw_blend::main::hf29870645e4656ef
                               at examples/draw/draw_blend.rs:4
  49:        0x106a0fbfe - std::rt::lang_start::{{closure}}::h394a5c713e84ced5
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  50:        0x1073ff678 - std::rt::lang_start_internal::{{closure}}::hab79accac7befc7d
                               at src/libstd/rt.rs:52
  51:        0x1073ff678 - std::panicking::try::do_call::he58e98df0f664580
                               at src/libstd/panicking.rs:303
  52:        0x107401dbb - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  53:        0x10740007a - std::panicking::try::h1c15a2595ce4d309
                               at src/libstd/panicking.rs:281
  54:        0x10740007a - std::panic::catch_unwind::h06858616dd2b84f7
                               at src/libstd/panic.rs:394
  55:        0x10740007a - std::rt::lang_start_internal::hfa21381d8ff23689
                               at src/libstd/rt.rs:51
  56:        0x106a0fbe1 - std::rt::lang_start::hf84070b83d2a38fd
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  57:        0x106a0d612 - draw_blend::view::hd8ac65399e0463c3

```
My guess is this is related to this:https://github.com/gfx-rs/wgpu-rs/commit/02f7ac9c02bf2e7313fa1b17a996b1a882a39a27

There are couple more of this error in example. I will add that info as I test them to run.

**Comment by mitchmindtree** [comment]
Thanks a lot for the report @wataru358! I think this is likely an error I must have introduced in #594. wgpu 0.5 introduces some tighter restrictions on bind group and pipeline layouts, I thought I had addressed them but I must have missed something. I'll investigate now!

**Comment by mitchmindtree** [comment]
This bug seems to be caused by the switch in render pipeline that is necessary in order to switch blend modes. I believe the issue is that currently, each time a pipeline is constructed, a new bind group layout is also constructed. In this example, when the blend mode is changed the render pipeline is changed and in turn a new bind group layout is created. In this case, the bind group layout is identical to the bind group layout in the previous render pipeline however it seems that the layout being equivalent is not enough. It seems that the bind group layout must have some unique identifier that must exactly match that with which the bind group itself is created.

I think the solution here is to separate the creation of bind group layouts from the creation of render pipelines, allowing a pipeline to re-use a layout in the case that only the blend mode has changed (as in our case). This should ensure the current render pipeline and bind group always refer to the same bind group layout instance.
