### ISSUE TITLE
Example draw_capture panics when running

### ISSUE THREAD

**Issue by wataru358** [nannou-org/nannou#614]
Steps to reproduce:
- Install rust & clone nannou per doc
- `cargo run --release --example draw_capture` or `cargo run --release --example draw_capture_hi_res`

Expected:
- Example runs

Actual:
- Example runs, but when interacting with window using mouse, you get the following message on CLI

```
user:examples username$ cargo run --release --example draw_capture
    Finished release [optimized] target(s) in 0.53s
     Running `/Users/username/personal/nannou/target/release/examples/draw_capture`
thread '<unnamed>' panicked at 'key not present', /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.8.2/src/lib.rs:834:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'key not present', /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.8.2/src/lib.rs:834:9
timed out while waiting for a worker thread to capture the frame
```
```
user:examples username$ cargo run --release --example draw_capture_hi_res
   Compiling examples v0.1.0 (/Users/username/personal/nannou/examples)
    Finished release [optimized] target(s) in 4.56s
     Running `/Users/username/personal/nannou/target/release/examples/draw_capture_hi_res`
thread '<unnamed>' panicked at 'key not present', /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.8.2/src/lib.rs:834:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

PS. @mitchmindtree Thanks for the fix on: https://github.com/nannou-org/nannou/pull/613
I pulled and confirmed the example working. I am still getting this issue after pulling the latest.

**Comment by mitchmindtree** [comment]
Thanks for the issue @wataru358!

Unfortunately I'm unable to recreate this issue on my Linux laptop - both examples seem to behave as expected even when moving the mouse around and resizing the window slightly (though if I resize too much I run into #491).

Could you provide a little info about what platform you're on and your GPU? Also if you have the time, could you possibly run the examples again, but this time with the `RUST_BACKTRACE=1` environment variable prefixed and post the output here? The back trace might help to hone in on the problem.

**Comment by wataru358** [comment]
Hi, sorry for late reply,

Here is what I can dig.
cargo 1.43.0 (2cbe9048e 2020-05-03)
rustc 1.43.1 (8d69840ab 2020-05-04)
MacBook Pro (15-inch, 2016)
Processor 2.9 Ghz Intel Core i7
Memory 16 GB 2133 MHz LPDDR3
Intel HD Graphics 530 1536 MB
If anything else needed, please let me know.

Thanks!

**Comment by sbauer322** [comment]
I've similar specs, but have not been reproduce this problem from commit around early June 2e1202320972b07e37d9a8c716c2c5c281858608 or a more recent one of 92f1077cb510a1e0ba0ea368e2ba59bd242d8b57 ... though it seems to run particularly poorly without `--release`.

cargo 1.44.1 (88ba85757 2020-06-11)
rustc 1.44.1 (c7087fe00 2020-06-17)
MacBook Pro (16-inch, 2019)
Processor 2.3 GHz 8-Core Intel Core i9
16 GB 2667 MHz DDR4
AMD Radeon Pro 5500M 4 GB
Intel UHD Graphics 630 1536 MB
