### ISSUE TITLE
Generative Design p_1_2_2_01 crashes when sorting saturation on the first image

### ISSUE THREAD

**Issue by sbauer322** [nannou-org/nannou#633]
Appears to consistently happen on the initial image loaded when you press the 3 key to sort the saturation. Doesn't seem to always happen on the other images, however.

```
/Users/sbauer/.cargo/bin/cargo run --color=always --package generative_design --example p_1_2_2_01
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
     Running `target/debug/examples/p_1_2_2_01`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', generative_design/color/p_1_2_2_01.rs:207:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
  13: core::panicking::panic
  14: core::option::Option<T>::unwrap
             at /Users/sbauer/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/macros/mod.rs:34
  15: p_1_2_2_01::sort_colors::{{closure}}
             at generative_design/color/p_1_2_2_01.rs:207
  16: alloc::slice::<impl [T]>::sort_by::{{closure}}
             at /Users/sbauer/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/slice.rs:254
  17: alloc::slice::insert_head
             at /Users/sbauer/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/slice.rs:761
  18: alloc::slice::merge_sort
             at /Users/sbauer/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/slice.rs:1003
  19: alloc::slice::<impl [T]>::sort_by
             at /Users/sbauer/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/slice.rs:254
  20: p_1_2_2_01::sort_colors
             at generative_design/color/p_1_2_2_01.rs:204
  21: p_1_2_2_01::view
             at generative_design/color/p_1_2_2_01.rs:115
  22: nannou::app::run_loop::{{closure}}
             at ./nannou/src/app.rs:1115
  23: <alloc::boxed::Box<F> as core::ops::function::FnMut<A>>::call_mut
             at /Users/sbauer/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/boxed.rs:1015
  24: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/sbauer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/app_state.rs:71
  25: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/sbauer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/app_state.rs:172
  26: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/sbauer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/app_state.rs:330
  27: winit::platform_impl::platform::observer::control_flow_end_handler
             at /Users/sbauer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/observer.rs:135
  28: _ZL12preoptimized
  29: _ZL12preoptimized
  30: _ZL12preoptimized
  31: _ZL12preoptimized
  32: _ZL12preoptimized
  33: _ZL12preoptimized
  34: _ZL12preoptimized
  35: _ZL12preoptimized
  36: _ZL12preoptimized
  37: _ZL12preoptimized
  38: <() as objc::message::MessageArguments>::invoke
             at /Users/sbauer/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128
  39: objc::message::platform::send_unverified
             at /Users/sbauer/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27
  40: objc::message::send_message
             at /Users/sbauer/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178
  41: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/sbauer/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/macros.rs:133
  42: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/sbauer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/macos/event_loop.rs:89
  43: winit::event_loop::EventLoop<T>::run
             at /Users/sbauer/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149
  44: nannou::app::run_loop
             at ./nannou/src/app.rs:1020
  45: nannou::app::Builder<M,E>::run
             at ./nannou/src/app.rs:471
  46: p_1_2_2_01::main
             at generative_design/color/p_1_2_2_01.rs:46
  47: std::rt::lang_start::{{closure}}
             at /Users/sbauer/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  48: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  49: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  50: std::panicking::try
             at src/libstd/panicking.rs:274
  51: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  52: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  53: std::rt::lang_start
             at /Users/sbauer/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  54: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 101
```

**Comment by sbauer322** [comment]
This might actually be a bug with conrod core's rgb_to_hsl function... I've opened an issue over there to verify.

**Comment by sbauer322** [comment]
This is definitely related to the saturation problem described in https://github.com/PistonDevelopers/conrod/issues/1370

A temporary work around is to check for NaN and replace the original partial compare line with:

```
if a_sat.is_nan() && b_sat.is_nan() {
    0.0.partial_cmp(&0.0).unwrap()
} else if a_sat.is_nan() {
    0.0.partial_cmp(&b_sat).unwrap()
} else if b_sat.is_nan() {
    a_sat.partial_cmp(&0.0).unwrap()
} else {
    a_sat.partial_cmp(&b_sat).unwrap()
}
```
