### ISSUE TITLE
Ubuntu X11: NoAvailableAdapter

### ISSUE THREAD

**Issue by Mec-iS** [nannou-org/nannou#653]
System: Ubuntu 18.04 LTS, default Xorg X11

Trying to run the laser stream example after installing and building according to the guide:
```
Finished release [optimized] target(s) in 3m 07s
     Running `target/release/examples/laser_frame_stream_gui`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailableAdapter', examples/laser/laser_frame_stream_gui.rs:150:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
~/creative/nannou$ cargo run --release --example laser_frame_stream
   Compiling examples v0.1.0 (/nannou/examples)
    Finished release [optimized] target(s) in 7.87s
     Running `target/release/examples/laser_frame_stream`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailableAdapter', examples/laser/laser_frame_stream.rs:41:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Seems like it can't create a window at:
```
    app.new_window()
        .size(240, 690)
        .key_pressed(key_pressed)
        .view(view)
        .build()
        .unwrap();
```
Which library or configuration I miissed?

**Comment by Mec-iS** [comment]
Didnt know Vulkan was required...

Fixed with `sudo apt-get install libvulkan1 mesa-vulkan-drivers vulkan-utils`

**Comment by DevinBayly** [comment]
@Mec-iS I seem to have gotten stuck at the same issue and the install line you suggested seems to not have an affect. 

I'm running an ubuntu 18.04 remote server with a portion of a v100 provided 

```
Wed Feb  3 21:54:40 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GRID V100X-4Q       On   | 00000000:00:06.0 Off |                  N/A |
| N/A   N/A    P0    N/A /  N/A |    304MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

When I run these commands I get the following error
``` 
ssh -X ubuntu_remote
cd ~/Documents/nannou
cargo run --release --example draw
cargo run --release --example draw
warning: use of deprecated associated function `image::DynamicImage::to_rgba`: replaced by `to_rgba8`
   --> nannou/src/wgpu/texture/image.rs:644:29
    |
644 |             let img = image.to_rgba();
    |                             ^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `image::DynamicImage::to_bgra`: replaced by `to_bgra8`
   --> nannou/src/wgpu/texture/image.rs:648:29
    |
648 |             let img = image.to_bgra();
    |                             ^^^^^^^

warning: use of deprecated associated function `image::DynamicImage::to_rgba`: replaced by `to_rgba8`
   --> nannou/src/wgpu/texture/image.rs:653:29
    |
653 |             let img = image.to_rgba();
    |                             ^^^^^^^

warning: 3 warnings emitted

warning: use of deprecated associated function `nannou::image::DynamicImage::to_rgba`: replaced by `to_rgba8`
   --> nannou_isf/src/pipeline.rs:238:40
    |
238 |                         .map(|img| img.to_rgba())
    |                                        ^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: 1 warning emitted

    Finished release [optimized] target(s) in 0.27s
     Running `target/release/examples/draw`
thread 'main' panicked at 'could not build default app window: NoAvailableAdapter', /home/exouser/nannou/nannou/src/app.rs:457:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I should mention that a Black window appears for a moment with the name of the example and the host machine in the window title before everything crashes.
![image](https://user-images.githubusercontent.com/11687631/106814813-32b33200-6630-11eb-9280-f73670576290.png)


Any assistance would be greatly appreciated!

**Comment by jakeisnt** [comment]
Having precisely the same issue despite installing all of the Vulkan dependencies - would appreciate this being reopened.
