### ISSUE TITLE
Error when resizing window completely

### ISSUE THREAD

**Issue by LowSpecCorgi** [nannou-org/nannou#690]
When resizing the window completely, in a bare bones program, I am met with the following error (with bactrace):
<details> 
  <summary>Error, condensed into summary tags, to make this issue less verbose</summary>

```rust
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `1`', /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.6/src/conv.rs:459:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: wgpu_core::conv::map_texture_dimension_size
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.6/src/conv.rs:459
   3: wgpu_core::device::Device<B>::create_texture
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.6/src/device/mod.rs:365
   4: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_texture
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.6/src/device/mod.rs:677
   5: wgpu_device_create_texture
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.5.1/src/device.rs:225
   6: wgpu::Device::create_texture
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.5.2/src/lib.rs:979
   7: nannou::wgpu::texture::Builder::build
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.15.0/src/wgpu/texture/mod.rs:559
   8: nannou::frame::create_lin_srgba_msaa_texture
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.15.0/src/frame/mod.rs:333
   9: nannou::frame::create_intermediary_lin_srgba
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.15.0/src/frame/mod.rs:357
  10: nannou::frame::RenderData::new
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.15.0/src/frame/mod.rs:300
  11: nannou::window::Window::rebuild_swap_chain
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.15.0/src/window.rs:1376
  12: nannou::app::run_loop::{{closure}}
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.15.0/src/app.rs:1182
  13: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}::{{closure}}
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:417
  14: winit::platform_impl::platform::sticky_exit_callback
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698
  15: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:406
  16: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/event_processor.rs:478
  17: winit::platform_impl::platform::x11::EventLoop<T>::drain_events
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:405
  18: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:282
  19: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:390
  20: winit::platform_impl::platform::EventLoop<T>::run
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:645
  21: winit::event_loop::EventLoop<T>::run
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149
  22: nannou::app::run_loop
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.15.0/src/app.rs:1020
  23: nannou::app::Builder<M,E>::run
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.15.0/src/app.rs:471
  24: nannou::app::SketchBuilder<E>::run
             at /home/basilicous/.cargo/registry/src/github.com-1ecc6299db9ec823/nannou-0.15.0/src/app.rs:496
  25: cc::main
             at ./src/main.rs:6
  26: core::ops::function::FnOnce::call_once
             at /home/basilicous/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details> 

Bear in mind, that I am using Linux, stable rust channel and `nannou = "0.15"`.

A gif demonstrating the problem:
![Peek 2020-12-13 19-20](https://user-images.githubusercontent.com/59167551/102021536-55d00c80-3d78-11eb-92b8-d6a5c3a74a3d.gif)

**Comment by super-continent** [comment]
Same error here on Windows, any progress on this? Seems like it shouldnt be a particularly difficult fix, unsure how to change it though.

**Comment by sidwellr** [comment]
The same thing happens (at least on Windows 10) when the window is minimized.
