### ISSUE TITLE
Examples don't run - Segfault

### ISSUE THREAD

**Issue by enaut** [nannou-org/nannou#742]
Hey, and thanks for the tool!
however I'm not able to run any example on Fedora 34 (on nvidia-proprietary, wayland, gnome40 in debug and release mode) they all crash with a segfault see the sample run with backtrace of the draw example:

```
❯ gdb target/debug/examples/draw
GNU gdb (GDB) Fedora 10.1-14.fc34
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from target/debug/examples/draw...
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/dietrich/Projekte/Source/nannou/target/debug/examples/draw.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) run
Starting program: /home/dietrich/Projekte/Source/nannou/target/debug/examples/draw 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff795c640 (LWP 7746)]
[New Thread 0x7ffff4883640 (LWP 7747)]
[New Thread 0x7fffe592b640 (LWP 7748)]
[New Thread 0x7fffe512a640 (LWP 7749)]
[New Thread 0x7fffe4929640 (LWP 7750)]
[New Thread 0x7fffcffff640 (LWP 7751)]
[New Thread 0x7fffcf7fe640 (LWP 7752)]
[New Thread 0x7fffc7fff640 (LWP 7753)]
[New Thread 0x7fffceffd640 (LWP 7754)]
[New Thread 0x7fffce7fc640 (LWP 7755)]
[New Thread 0x7fffcdffb640 (LWP 7756)]
[New Thread 0x7fffcd7fa640 (LWP 7757)]
[New Thread 0x7fffccff9640 (LWP 7758)]
[New Thread 0x7fffc77fe640 (LWP 7759)]
[New Thread 0x7fffc6ffd640 (LWP 7760)]
[New Thread 0x7fffc67fc640 (LWP 7761)]
[New Thread 0x7fffc5ffb640 (LWP 7762)]
[New Thread 0x7fffc57fa640 (LWP 7763)]
[New Thread 0x7fffc4ff9640 (LWP 7764)]
[New Thread 0x7fff97fff640 (LWP 7765)]
[New Thread 0x7fff977fe640 (LWP 7766)]
[New Thread 0x7fff96ffd640 (LWP 7767)]
[New Thread 0x7fff967fc640 (LWP 7768)]
[New Thread 0x7fff95ffb640 (LWP 7769)]
[New Thread 0x7fff957fa640 (LWP 7770)]
[New Thread 0x7fff94ff9640 (LWP 7771)]
[New Thread 0x7fff73fff640 (LWP 7772)]
[New Thread 0x7fff737fe640 (LWP 7773)]
[New Thread 0x7fff72ffd640 (LWP 7774)]
[New Thread 0x7fff727fc640 (LWP 7775)]
[New Thread 0x7fff71ffb640 (LWP 7776)]
[New Thread 0x7fff717fa640 (LWP 7777)]
[New Thread 0x7fff70ff9640 (LWP 7778)]
[New Thread 0x7fff5372b640 (LWP 7779)]
[New Thread 0x7fff52f2a640 (LWP 7780)]
[New Thread 0x7fff52729640 (LWP 7781)]
[New Thread 0x7fff51f28640 (LWP 7782)]

Thread 1 "draw" received signal SIGSEGV, Segmentation fault.
0x00007ffff7fb88e0 in wl_proxy_destroy (proxy=0x0) at ../src/wayland-client.c:528
528		struct wl_display *display = proxy->display;
Missing separate debuginfos, use: dnf debuginfo-install libedit-3.1-36.20210419cvs.fc34.x86_64
(gdb) bt
#0  0x00007ffff7fb88e0 in wl_proxy_destroy (proxy=0x0) at ../src/wayland-client.c:528
#1  0x00007ffff7664ac3 in wl_drm_destroy (wl_drm=<optimized out>) at src/egl/wayland/wayland-drm/wayland-drm-client-protocol.h:254
#2  device_select_find_wayland_pci_default (devices=devices@entry=0x5555575cad60, device_count=device_count@entry=2) at ../src/vulkan/device-select-layer/device_select_wayland.c:142
#3  0x00007ffff7664404 in get_default_device (pPhysicalDevices=<optimized out>, physical_device_count=2, selection=<optimized out>, info=<optimized out>) at ../src/vulkan/device-select-layer/device_select_layer.c:393
#4  device_select_EnumeratePhysicalDevices (instance=<optimized out>, pPhysicalDeviceCount=0x7fffffff3a84, pPhysicalDevices=0x0) at ../src/vulkan/device-select-layer/device_select_layer.c:456
#5  0x00007ffff770604b in setupLoaderTrampPhysDevs (instance=0x555557417d20) at ../loader/loader.c:6956
#6  0x00007ffff7710210 in vkEnumeratePhysicalDevices (instance=0x555557417d20, pPhysicalDeviceCount=0x7fffffff3ba4, pPhysicalDevices=0x0) at ../loader/trampoline.c:694
#7  0x000055555652cd32 in ash::vk::features::InstanceFnV1_0::enumerate_physical_devices (self=0x5555575a5ab8, instance=..., p_physical_device_count=0x7fffffff3ba4, p_physical_devices=0x0)
    at /home/dietrich/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.31.0/src/vk/features.rs:643
#8  0x00005555564cf7e9 in ash::instance::InstanceV1_0::enumerate_physical_devices<ash::instance::Instance> (self=0x5555575a5ab0) at /home/dietrich/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.31.0/src/instance.rs:423
#9  0x00005555564eafce in gfx_backend_vulkan::{{impl}}::enumerate_adapters (self=0x5555575ba860) at /home/dietrich/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.7.0/src/lib.rs:493
#10 0x0000555556075cf0 in wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::request_adapter<wgpu_core::hub::IdentityManagerFactory> (self=0x5555575ba860, desc=0x7fffffff5ce8, inputs=...)
    at /home/dietrich/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.7.1/src/instance.rs:691
#11 0x0000555555f3f22a in wgpu::backend::direct::{{impl}}::instance_request_adapter (self=0x5555575ba860, options=0x7fffffff6330) at /home/dietrich/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:681
#12 0x00005555561082d0 in wgpu::Instance::request_adapter (self=0x7fffffffc178, options=0x7fffffff6330) at /home/dietrich/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/lib.rs:1361
#13 0x0000555555801b78 in nannou::wgpu::device_map::{{impl}}::get_or_request_async::{{closure}} () at nannou/src/wgpu/device_map.rs:109
#14 0x0000555555849fbe in core::future::from_generator::{{impl}}::poll<generator-0> (self=..., cx=0x7fffffff6190) at /home/dietrich/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
#15 0x000055555580c9f5 in futures_executor::local_pool::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>> (cx=0x7fffffff6190)
    at /home/dietrich/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/local_pool.rs:315
#16 0x000055555580c71a in futures_executor::local_pool::run_executor::{{closure}}<core::option::Option<alloc::sync::Arc<nannou::wgpu::device_map::ActiveAdapter>>,closure-0> (thread_notify=0x7ffff79c97b0)
    at /home/dietrich/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/local_pool.rs:90
#17 0x00005555558cfd5f in std::thread::local::LocalKey<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>>::try_with<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>,closure-0,core::option::Option<alloc::sync::Arc<nannou::wgpu::device_map::ActiveAdapter>>> (self=0x555556ef8fd0, f=...) at /home/dietrich/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272
#18 0x00005555558cfad4 in std::thread::local::LocalKey<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>>::with<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>,closure-0,core::option::Option<alloc::sync::Arc<nannou::wgpu::device_map::ActiveAdapter>>> (self=0x555556ef8fd0, f=...) at /home/dietrich/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248
#19 0x000055555580c512 in futures_executor::local_pool::run_executor<core::option::Option<alloc::sync::Arc<nannou::wgpu::device_map::ActiveAdapter>>,closure-0> (f=...)
    at /home/dietrich/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/local_pool.rs:86
#20 0x000055555580c83e in futures_executor::local_pool::block_on<core::future::from_generator::GenFuture<generator-0>> (f=...)
    at /home/dietrich/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.15/src/local_pool.rs:315
#21 0x0000555555801967 in nannou::wgpu::device_map::AdapterMap::get_or_request (self=0x7fffffffc180, options=..., instance=0x7fffffffc178) at nannou/src/wgpu/device_map.rs:76
#22 0x0000555555803d45 in nannou::window::Builder::build (self=...) at nannou/src/window.rs:804
#23 0x0000555555769921 in nannou::app::Builder<(), nannou::event::Event>::run<(),nannou::event::Event> (self=...) at /home/dietrich/Projekte/Source/nannou/nannou/src/app.rs:476
#24 0x0000555555769edc in nannou::app::SketchBuilder<nannou::event::Event>::run<nannou::event::Event> (self=...) at /home/dietrich/Projekte/Source/nannou/nannou/src/app.rs:518
#25 0x000055555574fe2c in draw::main () at examples/draw/draw.rs:4
(gdb) 
```

**Comment by danwilhelm** [comment]
It seems like it's crashing when it's getting/requesting an adapter, but I'm surprised it just gives a generic segfault. Nannou is built on WGPU, which [currently requires Vulkan drivers on Linux](https://github.com/gfx-rs/wgpu#supported-platforms) -- do you have these installed?

**Comment by enaut** [comment]
Mhm I can't solve it... I had quit some i686 binaries installed on my x_64 install... I removed them... but now vulkaninfo creashes with the same segfault... - I think... so this is probably driver related or something? - I tried reinstalling all the related packages but nothing helped so far... I'll wait for the next kernel update... maybe the issue will be resolved then - if not I may dive deeper into the problem but I think it is not nannou related in any case so I'll close this here.
