### ISSUE TITLE
Occasional crash on latest version of `nannou` - wgpu error

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/nannou#761]
Normally occurs between 5-10 minutes after starting to run, the exact location of the wgpu error seems to change. It happened once during a draw call within the previs, the following two times it occurred within the GUI render pass.

Here's one occasion with `RUST_BACKTRACE=1`

![Screenshot from 2021-06-27 13-29-47](https://user-images.githubusercontent.com/4587373/123542834-f6ea4780-d74b-11eb-87bd-a6e4e7325639.png)

Here's one with `RUST_BACKTRACE=full`

![Screenshot from 2021-06-27 13-44-33](https://user-images.githubusercontent.com/4587373/123543396-6eb97180-d74e-11eb-8216-7b3bb1e60f64.png)

**Comment by mitchmindtree** [comment]
Can confirm it also occurs on my laptop:

```
     Running `/home/mindtree/programming/rust/morph/sw/target/release/morph-te`
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Handling wgpu errors as fatal by default', /home/mindtree/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.9.0/src/backend/direct.rs:1978:5
stack backtrace:
   0:     0x5573f95aa8d0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5573f95aa8d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5573f95aa8d0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5573f95aa8d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5573f95cf26f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x5573f95a2f02 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x5573f95acdf5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5573f95acdf5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5573f95acdf5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x5573f95ac8a3 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x5573f95ad3fd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x5573f917b044 - std::panicking::begin_panic::{{closure}}::ha5ae9b3257c5581d
  12:     0x5573f917afdc - std::sys_common::backtrace::__rust_end_short_backtrace::hb64f2c3ad650bd7a
  13:     0x5573f89a73bc - std::panicking::begin_panic::h92eee0309daf140f
  14:     0x5573f92ddfca - wgpu::backend::direct::default_error_handler::hf7b613c00af3f4f7
  15:     0x5573f92d0f85 - core::ops::function::Fn::call::h9f8348ab9e3fb9cc
  16:     0x5573f92dacd1 - <wgpu::backend::direct::Context as wgpu::Context>::device_create_buffer::h1092181b61d3ce9b
  17:     0x5573f917058a - <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hb91419da84349c0c
  18:     0x5573f910d8f9 - conrod_wgpu::Renderer::render::he8165e0e38690caf
  19:     0x5573f8f26831 - nannou::ui::encode_render_pass::h9a685f61fe2eeb93
  20:     0x5573f8f2638c - nannou::ui::Ui::draw_to_frame::h5eb95b5da5072231
  21:     0x5573f8da6177 - morph_te::gui_view::h1f1470c68186ae83
  22:     0x5573f8d814fc - nannou::app::run_loop::{{closure}}::h99188ab502a70c2b
  23:     0x5573f8d80017 - winit::platform_impl::platform::x11::EventLoop<T>::run::h2e18c8e9e6c8c387
  24:     0x5573f8d7f966 - winit::platform_impl::platform::EventLoop<T>::run::h2b71813adcec3f0b
  25:     0x5573f8aca372 - winit::event_loop::EventLoop<T>::run::h4c475af8e91bedc4
  26:     0x5573f8ad09ee - nannou::app::Builder<M,E>::run::h781a7b60c52892c8
  27:     0x5573f8d99057 - morph_te::main::hab353410786781be
  28:     0x5573f8b7c7e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8d2441e1aa7f383d
  29:     0x5573f8b7d3a9 - std::rt::lang_start::{{closure}}::h8acc0ab5a04b3108
  30:     0x5573f95ad8fa - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  31:     0x5573f95ad8fa - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  32:     0x5573f95ad8fa - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  33:     0x5573f95ad8fa - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  34:     0x5573f95ad8fa - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  35:     0x5573f8dac902 - main
```

**Comment by mitchmindtree** [comment]
Could potentially be due to a vram leak - memory seems to consistently rise throughout the runtime of the program.

**Comment by mitchmindtree** [comment]
Sorry I just realised I posted this to nannou rather than our installation repo!

For context, the above errors are occurring in one of our installations driven by nannou. It seems there's a pretty severe memory leak in wgpu 0.9 https://github.com/gfx-rs/wgpu/issues/1501. We've been able to work around it by adding a patch to use wgpu 0.8 instead.

**Comment by mitchmindtree** [comment]
Sorry I just realised I posted this to nannou rather than our installation repo!

For context, the above errors are occurring in one of our installations driven by nannou. It seems there's a pretty severe memory leak in wgpu 0.9 https://github.com/gfx-rs/wgpu/issues/1501. We've been able to work around it by adding a patch to use wgpu 0.8 instead.
