### ISSUE TITLE
RequestDeviceError on WSL2

### ISSUE THREAD

**Issue by gvcallen** [nannou-org/nannou#927]
I am tried running the Nannou Polyline example on my Ubuntu WSL2, but am met with the following error in the terminal:
`thread 'main' panicked at 'could not get or request device: RequestDeviceError', nannou_wgpu/src/device_map.rs:220:14`

I am successfully able to run the wgpu "cube" example, so I don't think its an issue with my system.

After some investigating, I noticed the error on the lower level occurs in wgpu-core/src/instance.rs when calling `adapter.create_device`. Here, with the wgpu cube example, the device is created successfully. However, through nannou, the resultant error variable contains the following fields:
`
name: "max_storage_buffer_size"
requested: 134217728
allowed: 0
`

My PC has onboard Intel i7-1065G7 graphics. I noticed that the wgpu example requested a storage buffer size of 0.

**Comment by mhfowler** [comment]
I'm also seeing this error while running the first nannou example on debian.

```
     Running `target/release/examples/draw`
thread 'main' panicked at /home/notplants/computer/projects/nannou-brush/nannou/nannou_wgpu/src/device_map.rs:224:14:
could not get or request device: RequestDeviceError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault
```
